Revert PR 328
polylang/xliff-exporter-stubs pull request #2
Opened 2022-05-02 07:01 UTC by manooweb

Regenerate xliff-exporter stubs after reverting the [xliff-exporter PR 328](https://github.com/polylang/xliff-exporter/pull/341)

2022-05-02 15:03 UTC, Marianne380 requested changes

2022-05-02 15:03 UTC, Marianne380 commented on xliff-exporter-stubs.php
> +     * @return string|false
Why this change here?

2022-05-03 07:10 UTC, manooweb commented on xliff-exporter-stubs.php
> +     * @return string|false
It comes from another PR (https://github.com/polylang/xliff-exporter/pull/336/files#diff-f07700c6a524e5841a11466e8f680604d7b54cb432fcb575c7451939790067c8) which is merged before the stubs was regenerated.

2022-05-03 10:43 UTC, Marianne380 approved these changes

2022-05-05 16:53 UTC, merged